server:
  # If you are using symfony 5.3+ and the new Runtime component:
  # remove the previous `command` line above and uncomment the line below.
  command: "php public/index.php"
  env:
    APP_ENV: "prod"
    APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8081
  middleware: [ "gzip" ]
  pool:
    num_workers: 1

logs:
  mode: production
  channels:
    http:
      level: error # Log all http requests, set to info to disable
    server:
      level: error # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: error

# Uncomment to use metrics integration
# rpc:
#   listen: tcp://127.0.0.1:6001

# Uncomment to use metrics integration
# metrics:
#   # prometheus client address (path /metrics added automatically)
#   address: "0.0.0.0:9180"
